import Layout from '@/component/layout/Layout'
import BlogDetailsMain from '@/component/main/BlogDetailsMain'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'

const blogDetails = () => {
  const router = useRouter(); // Initialize the router
  const { id } = router.query; // Get the productId from the query parameters

  const [product, setProduct] = useState(null);
  useEffect(() => {
    // Fetch the product data from your API here
    async function fetchProductData() {
      try {
        const response = await fetch(`/api/blogs/${id}`); // Make sure your API route matches the path
        if (response.ok) {
          const productData = await response.json();
          setProduct(productData);
        } else {
          // Handle error
          console.log({message:'Error occured fetching blog'});
        }
      } catch (error) {
        // Handle error
        console.log({message:'Blog Api call error'});
      }
    }

    if (id) {
      fetchProductData();
    }
  }, [id]);

  return (
    <>
      <Head>
        <title>Blog Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <>
        {product && (
          <Layout>
            <BlogDetailsMain product={product} />
          </Layout>
        )
        }
      </>
    </>
  )
}

export default blogDetails