// app/layout.js
import 'bootstrap/dist/css/bootstrap.min.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import '../styles/css/all.min.css';
import 'swiper/scss';
import 'swiper/scss/navigation';
import 'swiper/scss/pagination';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/css/style.css';
import '../styles/scss/style.scss';

import { VerdaContextProvider } from '@/context/VerdaContext';
import { ToastContainer } from 'react-toastify';
import RightSideBar from '@/component/sidebar/RightSideBar';

export const metadata = {
  title: 'Verda', // <-- You can make this dynamic later
  description: 'Generated by Verda App',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <VerdaContextProvider>
          {children}
          <RightSideBar />
          <ToastContainer />
        </VerdaContextProvider>
      </body>
    </html>
  );
}
