import Head from 'next/head';
import { useRouter } from 'next/router'; // Import the useRouter hook
import { useEffect, useState } from 'react';
import ProductDetailsMain from '../../component/main/ProductDetailsMain';

const ProductDetails = () => {
  const router = useRouter(); // Initialize the router
  const { id } = router.query; // Get the productId from the query parameters

  const [product, setProduct] = useState(null);
  const [allProduct,setAllProduct] = useState([])
  useEffect(() => {
    async function fetchProducts() {
      try {
        const response = await fetch('/api/products');
        if (response.ok) {
          const data = await response.json();
         setAllProduct(data); // Store fetched data in productDataList
        } else {
          console.error('Failed to fetch products');
        }
      } catch (error) {
        console.error('Error fetching products:', error);
      }
    }
  
    fetchProducts();
  }, []);
  useEffect(() => {
    // Fetch the product data from your API here
    async function fetchProductData() {
      try {
        const response = await fetch(`/api/products/${id}`); // Make sure your API route matches the path
        if (response.ok) {
          const productData = await response.json();
          setProduct(productData);
        } else {
          // Handle error
          console.log({message:'error occured fetching product'});
        }
      } catch (error) {
        // Handle error
        console.log({message:'no product found'});
      }
    }

    if (id) {
      fetchProductData();
    }
  }, [id]);

  return (
    <>
      <Head>
        <title>Verda Shop Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      {product && <ProductDetailsMain product={product} allProduct={allProduct}/>}
    </>
  );
};

export default ProductDetails;
