import ProductDetailsMain from '@/component/main/ProductDetailsMain';
import { allProductList } from '@/data/Data';

export const metadata = {
  title: 'Verda Shop Details',
  description: 'Generated by create next app',
};

export default async function ProductDetailsPage({ params }) {
  const { id } = params;

  // Find the individual product
  const product = allProductList.find(p => p.slug.toString() === id);

  if (!product) {
    // Optionally return a 404 or custom error UI
    return <p>Product not found</p>;
  }

  return <ProductDetailsMain product={product} allProduct={allProductList} />;
}
