import Head from 'next/head';
import { useRouter } from 'next/router'; // Import the useRouter hook
import { useEffect, useState } from 'react';
import ProductDetailsMain from '../../component/main/ProductDetailsMain';

const ProductDetails = () => {
  const router = useRouter(); // Initialize the router
  const { id } = router.query; // Get the productId from the query parameters

  const [ornament, setOrnament] = useState(null);
  const [allOrnament,setAllOrnament] = useState([])
  useEffect(() => {
    async function fetchOrnaments() {
      try {
        const response = await fetch('/api/ornaments');
        if (response.ok) {
          const data = await response.json();
         setAllOrnament(data); // Store fetched data in OrnamentDataList
        } else {
          console.error('Failed to fetch Ornaments');
        }
      } catch (error) {
        console.error('Error fetching Ornaments:', error);
      }
    }
  
    fetchOrnaments();
  }, []);
  useEffect(() => {
    // Fetch the Ornament data from your API here
    async function fetchOrnamentData() {
      try {
        const response = await fetch(`/api/ornaments/${id}`); // Make sure your API route matches the path
        if (response.ok) {
          const OrnamentData = await response.json();
          setOrnament(OrnamentData);
        } else {
          console.log('no ornament found');
        }
      } catch (error) {
        console.log('no ornament found');
      }
    }

    if (id) {
      fetchOrnamentData();
    }
  }, [id]);

  return (
    <>
      <Head>
        <title>Verda Shop Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      {ornament && <ProductDetailsMain product={ornament} allProduct={allOrnament}/>}
    </>
  );
};

export default ProductDetails;
